FROM openresty/openresty:alpine

# Instalar dependencias
RUN apk add --no-cache redis

# Crear directorios para Lua y configuración
RUN mkdir -p /usr/local/openresty/nginx/conf/lua

# Copiar configuración de Nginx
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY lua/redis_cache.lua /usr/local/openresty/nginx/conf/lua/redis_cache.lua

# Exponer puerto HTTP
EXPOSE 80
